src/components/RequestgroupsList.vue
The API call to get requestgroups was being triggered twice on page load, once in the created hook, and then a second time because the value of `rgQueryParams.limit` got changed from `20` to `"20"` when merging the query parameters of the page itself into the query parameters that were sent along with the API call, so the `rgQueryParams.limit` watcher sent off a second API request. 
To fix that problem, merging the page query parameters into `rgQueryParams` is now instead done in the component data initialization. I also actually ended up removing the watchers and switched to using callbacks for when a user inputs a new value into the limit dropdown or selects a new page in the pagination element. I just find that to be much easier to reason about especially since there are a few …
=> Fix duplicate requestgroups API calls on page load

src/components/Configuration.vue
Pull over the [changes that were made to a Vue component to allow a user to select muscat guide modes in the observation-portal](https://github.com/observatorycontrolsystem/observation-portal/pull/160) so that it continues to work in the new frontend.
=> Show guide mode options for muscat

src/components/Window.vue
Add more information to the jitter help text.
=> Update jitter help text

src/components/Target.vue
Fixed the call to simbad - the url in the app configuration was not being passed through to the component where it is used.
=> Use simbad url that is set in the configuration

src/components/RequestgroupsList.vue
Ref. [issue 1393](https://lcoglobal.redmineup.com/issues/1393)
Tim noted that he was not able to distinguish his proposals by name and the inclusion of the code would help matters.
The Python developer in me opted to use a [template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) to construct the dropdown text, but I am totally open to better alternatives.
I've deployed this change to the dev frontend at http://observation-portal-dev.lco.gtn
=> Add proposal code to filter dropdown

package-lock.json, package.json
This updates the observation-portal-frontend to use the updated RequestGroups List component, which contains additional filtering options.
This branch is currently deployed at http://observation-portal-dev.lco.gtn
lco-observation-portal PR: https://github.com/LCOGT/observation-portal-project/pull/4
=> Update to ocs-component-lib 0.6.0

src/components/InstrumentConfig.vue
Fixes https://lcoglobal.redmineup.com/issues/1428
Simple interface submission was never updated to work for muscat. This PR sets the optical elements available for muscat submission when the a client is using the simple interface. The optical elements are hard coded like this for the simple interface since the clients are not supposed to be able to see all the options to keep it simple.
Ultimately this fix will be superseded when this project is updated to use the compose page component from the component lib, but I did it like this here anyway to get the fix out there.
=> Fix simple interface muscat submission

src/components/ArchiveTable.vue
Curtis keeps finding bugs in things!
From a Slack conversation:
I went into the logic and noticed some outdated stuff with respect to reduction levels. Since the portal only reports raw/reduced, I kept that convention. I just updated so that anything not RLEVEL=0 is reduced. Also removed quicklook since that's not a thing anymore.
I couldn't find anything else that referenced quicklook, so I think this is the only place?
I've got this running on http://observation-portal-dev.lco.gtn/
Example request with reduced data: http://observation-portal-dev.lco.gtn/requests/1889951
Also confirmed to work on -92 data:
=> Simplify logic for determining reduction level in ArchiveTable.

src/views/Apply.vue, src/views/Compose.vue, src/views/Help.vue
The Feb 2022 version of the Getting Started Guide was deployed on Feb 1.
=> Fix links to Getting Started Guide

src/views/ProposalDetail.vue
This adds information to the proposal detail page for Co-Investigators so that they can see how much time they've been allotted and how much they've used.
There are three cases:
1. User is a PI - this is not shown. Nothing has changed.
2. User is a CI _with_ a time limit - a progress bar with hours used/hours allocated is shown
3. User is a CI _without_ a time limit -  Hours used are shown, and a message _"The Principal Investigator has not set a time limit for this Co-Investigator. "_
I have this deployed to http://observation-portal-dev.lco.gtn
I've set up a few proposals for the eng user (usual sba password) to demo this functionality. Login with eng and visit the following pages:
Case 1: [User is a PI](http://observation-portal-dev.lco.gtn/proposals/TOM%20demo%20scheduler?role=CI&propo …
=> Add Co-Investigator Time Allocation Information

package-lock.json, package.json, src/views/Compose.vue
This uses the `target-fields-footer` slot from here: https://github.com/observatorycontrolsystem/ocs-component-lib/pull/22 to add the `fractional_ephemeris_rate` field if its a non-major planet orbital elements type target. 
This took me a little while to figure out and I still don't fully understand how this vue stuff works, but this seems to do what I want when I'm testing locally.
=> Add fractional_ephemeris_rate field into the compose page

src/components/EditSciApplication.vue
Report on past use and list of publication should begin on a new page, so that these items (which reveal author identities) can be separated from the justification sections.
=> Instruction to start new page in pdf

src/archive.js, src/components/Archive.vue, src/components/ArchiveTable.vue, src/components/RequestDetail.vue, src/views/ProposalDetail.vue
This isn't needed immediately but we should deploy this before removing the old filters and fields from the archive frames response.
=> Update archive filters

src/views/Compose.vue
Forgot to make this change with the obs portal moon phase story but caught it in integration testing. At least we made it really easy to add these parameters back to the UI in the component library!
=> Add moon phase to the UI

src/archive.js
This is to match user expectations, as the guide frames are excluded from the tables/lists in the obs portal frontend.
=> Exclude GUIDE frames from downloads from the obs portal

src/main.js
When users are logged out, they do not have a profile.tokens.api_token, and this is being sent to the archive API as undefined. This causes auth to fail. In reality, we want this to not send any authorization headers since the user is logged out. 
This matches [the behavior in the archive frontend](https://github.com/observatorycontrolsystem/science-archive-client/blob/d39eeb48f313715ebb726e5bbbd170bb31e49d3a/src/main.js#L46) as well.
Deployed to http://observation-portal-dev.lco.gtn - confirmed that logged in, the auth token is sent, logged out, no auth header/token is sent.
=> Do not add undefined api token to headers of request to archive API

src/components/RequestgroupsList.vue
Emily says: Not urgent, but a user alerted me to the fact that the Observation Portal's "Contact Support" link goes to scisupport@lco.global (which is incorrect).  Could someone please change it to science-support@lco.global when they get a second?
=> Fix mailto link on homepage

src/components/EditSciApplication.vue
This should avoid getting API errors when saving partial proposals.
=> do not post observing budget entries w/ invalid instrument types

package-lock.json, package.json, src/components/ArchiveTable.vue
At some point after bootstrap-table v1.20, it appears that support for bootstrap<5 was dropped and this broke our rows per page dropdown. Since we were using a caret spec for the dependency, we were all the way up at 1.24.x, so constrain our version to patch versions within 1.19.x.
https://github.com/user-attachments/assets/1a3231d7-fd1c-46a6-aff3-41cab1ded735
=> Fix rows per page dropdown

README.md, src/components/InstrumentConfigForm.vue
This displays a warning for users if they select a filter/readout mode combination that is unable to be automatically reduced.
There's some bespoke logic in here, but I think it's decently minimal and simple to modify as other instruments are added or policy changes.
https://github.com/user-attachments/assets/997ee8b8-44bd-4ab3-957b-dd57fc631472
=> Add alert and check for sinistro filter/readout mode combinations

src/views/ProposalDetail.vue
A user noticed that his Co-Is could only see how much time was left in their allocation rounded down to the nearest hour, even though one decimal place is displayed.  This meant that if a Co-I had 8.9 hours left, they were led to believe they only had 8.0 hours, which affected their ability to plan their program (see attached screenshot).
I propose that we round to the nearest tenth of an hour to give the user +/- 3 min accuracy in knowing how much time they have left.
=> Improved Co-I Allocation Rounding
